Return-Path: <jailhouse-dev+bncBCJI7SMNV4NBBXVEX3ZAKGQEDZ6SQ3A@googlegroups.com>
X-Original-To: lists+jailhouse-dev@lfdr.de
Delivered-To: lists+jailhouse-dev@lfdr.de
Received: from mail-ed1-x53f.google.com (mail-ed1-x53f.google.com [IPv6:2a00:1450:4864:20::53f])
	by mail.lfdr.de (Postfix) with ESMTPS id 24DC31673FD
	for <lists+jailhouse-dev@lfdr.de>; Fri, 21 Feb 2020 09:18:39 +0100 (CET)
Received: by mail-ed1-x53f.google.com with SMTP id n12sf1023946edq.13
        for <lists+jailhouse-dev@lfdr.de>; Fri, 21 Feb 2020 00:18:39 -0800 (PST)
ARC-Seal: i=2; a=rsa-sha256; t=1582273119; cv=pass;
        d=google.com; s=arc-20160816;
        b=B1/TfR6ZC+zRtblgi0vVPPkFILsY/UhsJpVeE+1ZLjJh4YbgKYFtIRfHSA6vMuFRVy
         CwteAfb5dVE6Zm4/GV3KoxQk96/sLlt4WGVCdleTang2ZXb8C9cpcdN3H3l4U2deqtex
         sZAaNhgQXflTb6ZYQlhKs6gKRvVXVKrOFTGyIeDcJGNdjbxOFRog9CDwhSVLgTYQBD9t
         k/jzxkMMSwOBrR13mLcRbKPadxxg1MVVqC1SZej5lAVOoXT646OksxJcreglrkQt20q7
         urKb+i5UavgmxsxTJMSyUCqLa75yc0/s6f0MozlCQijVObrAA+na01Icp/f4ijdyAiBn
         BICQ==
ARC-Message-Signature: i=2; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-subscribe:list-archive:list-help:list-post
         :list-id:mailing-list:precedence:content-transfer-encoding
         :content-language:in-reply-to:mime-version:user-agent:date
         :message-id:from:references:to:subject:sender:dkim-signature;
        bh=JMoF41Z2JqLBTEVevoCzaiFDs5ShREswJDqs38u0MOY=;
        b=DX1/NzpMTHqStixieOqaM0lqK5qPzVGqVNHDvmEhfDGeRHSJjz7t0T40ko5NSaIRJ1
         XXtVGqpz0wGvj7Qtwg9klEOYY9PSswdIpUpaPf3tZY/zQYcAB4dRA7oyV3KD76mMPPgJ
         fR2U39o0RvMy/qNgs6B9UHCUx3qtUwrN6egY/QLqV19Et5RiaZw4NJnLozX5skMmoWH0
         WPWBUq6Uw+7xgSaRi1gfHUhtaFiDbHdPJRvAbz/GaHkJ/HtIJeelC7/QBFDEIpQ+SBYj
         mcWgxjvbpPPt6fcznHyQCE3g37/wPr7QmGHrmx8wbLe/Ys2I2wLpTAiyzjS8e7X1rTH3
         LokQ==
ARC-Authentication-Results: i=2; gmr-mx.google.com;
       spf=pass (google.com: domain of jan.kiszka@siemens.com designates 192.35.17.2 as permitted sender) smtp.mailfrom=jan.kiszka@siemens.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=siemens.com
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=googlegroups.com; s=20161025;
        h=sender:subject:to:references:from:message-id:date:user-agent
         :mime-version:in-reply-to:content-language:content-transfer-encoding
         :x-original-sender:x-original-authentication-results:precedence
         :mailing-list:list-id:list-post:list-help:list-archive
         :list-subscribe:list-unsubscribe;
        bh=JMoF41Z2JqLBTEVevoCzaiFDs5ShREswJDqs38u0MOY=;
        b=gulYckLMkCkYH8YbyW9bug9yccHgFWIKcCdOeBLfA3Rq9Sdqqwh+xvugYfWCK7rpeN
         Xih9qjclgKCExyFxpAP444YXSZvOkw9vI2eMMhlS7A/Tv3yGSuYBFfo97BBz6dYUAyBr
         +/V6W+cVb0BPthRtvwo0pI/PMqWilYJVi0cSyrymqpiH7S3xbaB+2C+TWPXWs6P3Z7wd
         egolpCgnlrOIkmcQsBJs2PWvlq679F316culArAoeKpRDTSRSXiz6vxhPwFdzy96ih23
         goHYmnTBNF0ourZBJNM6QNOXufMOOmPPwyptpi8g/hUWl2PPYVaOi0bnjgaGbj1DbsY9
         dByQ==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=sender:x-gm-message-state:subject:to:references:from:message-id
         :date:user-agent:mime-version:in-reply-to:content-language
         :content-transfer-encoding:x-original-sender
         :x-original-authentication-results:precedence:mailing-list:list-id
         :x-spam-checked-in-group:list-post:list-help:list-archive
         :list-subscribe:list-unsubscribe;
        bh=JMoF41Z2JqLBTEVevoCzaiFDs5ShREswJDqs38u0MOY=;
        b=cfeDMGLL9ahpzvw2cg2swUEgox+xwkn873jRCj9wObFvj+jPPxAURW+cv6DB57pMGs
         +ucvPZyQ8WT6zg3bq3TIhiOGaz88lllcP40jGORE67e9DXzQwNDjMzTwViB5JUX3QXkP
         74hj9aWWUNgSMCuWiSBStHqZ92w1C/lxitX6SQEZG/qCzsgzJx1ip5EdL56Kkye7aMxd
         PbSF7tZC6KpH1dfLMra0RSNZqQ3LbhHsaXvB/btRwRKE+OgimwjWzXC/Yyt385LTlSrA
         egyAvlaAjcVvleLxGWNQhaapgbOkeBHxeOLP0CUV/jhbb4NFhVu6KOrIjzGQDr8c62JC
         Ri4Q==
Sender: jailhouse-dev@googlegroups.com
X-Gm-Message-State: APjAAAWKFQwuYVTq0tlnHnCC9aal0TPoDUGfFG8gYf0e3n37wVqDoKEm
	oV6FtRimcITYmjzXDXSs0tY=
X-Google-Smtp-Source: APXvYqxo30/nl1JQPhi0q30sK4gvBjpuDrTTmrQxeVHf+3XLCbhHv0MWmI/wEdW+nGQ/GL15mLtEOA==
X-Received: by 2002:a05:6402:17fb:: with SMTP id t27mr32529885edy.159.1582273118813;
        Fri, 21 Feb 2020 00:18:38 -0800 (PST)
X-BeenThere: jailhouse-dev@googlegroups.com
Received: by 2002:a17:906:8597:: with SMTP id v23ls547362ejx.6.gmail; Fri, 21
 Feb 2020 00:18:38 -0800 (PST)
X-Received: by 2002:a17:906:807:: with SMTP id e7mr33577898ejd.381.1582273117977;
        Fri, 21 Feb 2020 00:18:37 -0800 (PST)
ARC-Seal: i=1; a=rsa-sha256; t=1582273117; cv=none;
        d=google.com; s=arc-20160816;
        b=gbkjFcJghkTanwARiIKBA0lRKxTZyCNk6GDSuIjhY3VjhZBpaKzhhFwYIY+76ivHIM
         oAI9hXLsRGyRnP+VrK6YZeqjOEZghHsFc1yRnLOb5qWS8I7RedKiefDSI+E7lZ0pfiGJ
         hZnwJvAdNveElkArswPpKVtOp3PPDRAJ7Lw3rzQ6R8o4MzBuRNxGfiCU6exSANXnhTN3
         19Eal/yKjrYW9lY7Fqi5dtXXC36E+JppA9CEgbEZ/RJdV+VUJ326VDPTuaMMcG0sMdav
         QmlVMdD3uE54aJOHY5C5wi1lj4owM3WgmmMAt+/f/05+Va/eiaC87N67Oo700n4GaHaR
         Mjjw==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=content-transfer-encoding:content-language:in-reply-to:mime-version
         :user-agent:date:message-id:from:references:to:subject;
        bh=TCr1qwyIRyevA9Cx23Tcm8OkgD7Z+plSG4qVA5I5cys=;
        b=LQE4HdoJeSrVtuXoUnNtqQom1DiO7ZhbyMl9ToCn91o+QBoSp1IcfBwxUE1U1XI1RX
         jEWh11sFhgqmwBI6Ad0dy+MWvNt/4jgcoTz7N08Bg3fvp8ipdKnNlLs637Tqo/c46gjf
         VtJ4y0GgCw9vGxo5XlYL09IhBs99f6HHR5nnFzbiMBXG/KHdelCQwhKaCC3jN63d+gD2
         etOQTKxUbnGsiMQuYcc7cFvqglccq4o56v0nMJgE3nuLTmqED1FeJmzsslTOaglyBGjK
         kgbh12Bi7xv2dmfjWoos0DhD5xc1AbB898ITavML3WqQkoguRWygiO4O1okEmhhNzNYv
         oCcQ==
ARC-Authentication-Results: i=1; gmr-mx.google.com;
       spf=pass (google.com: domain of jan.kiszka@siemens.com designates 192.35.17.2 as permitted sender) smtp.mailfrom=jan.kiszka@siemens.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=siemens.com
Received: from thoth.sbs.de (thoth.sbs.de. [192.35.17.2])
        by gmr-mx.google.com with ESMTPS id d29si89085edj.0.2020.02.21.00.18.37
        for <jailhouse-dev@googlegroups.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 21 Feb 2020 00:18:37 -0800 (PST)
Received-SPF: pass (google.com: domain of jan.kiszka@siemens.com designates 192.35.17.2 as permitted sender) client-ip=192.35.17.2;
Received: from mail2.sbs.de (mail2.sbs.de [192.129.41.66])
	by thoth.sbs.de (8.15.2/8.15.2) with ESMTPS id 01L8Iah1021582
	(version=TLSv1.2 cipher=DHE-RSA-AES256-GCM-SHA384 bits=256 verify=OK);
	Fri, 21 Feb 2020 09:18:36 +0100
Received: from [167.87.145.172] ([167.87.145.172])
	by mail2.sbs.de (8.15.2/8.15.2) with ESMTP id 01L8IYuo012947;
	Fri, 21 Feb 2020 09:18:35 +0100
Subject: Re: Need help to configure non-root linux cell configuration and dts
 file for jetson tx2
To: Saroj Sapkota <samirroj2016@gmail.com>,
        Jailhouse <jailhouse-dev@googlegroups.com>
References: <84e4bb7d-006b-408d-962b-a5348114fb81@googlegroups.com>
From: Jan Kiszka <jan.kiszka@siemens.com>
Message-ID: <99884b63-2e40-3b64-86fa-ff2d9c8457a9@siemens.com>
Date: Fri, 21 Feb 2020 09:18:34 +0100
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101
 Thunderbird/68.5.0
MIME-Version: 1.0
In-Reply-To: <84e4bb7d-006b-408d-962b-a5348114fb81@googlegroups.com>
Content-Type: text/plain; charset="UTF-8"; format=flowed
Content-Language: en-US
Content-Transfer-Encoding: base64
X-Original-Sender: jan.kiszka@siemens.com
X-Original-Authentication-Results: gmr-mx.google.com;       spf=pass
 (google.com: domain of jan.kiszka@siemens.com designates 192.35.17.2 as
 permitted sender) smtp.mailfrom=jan.kiszka@siemens.com;       dmarc=pass
 (p=NONE sp=NONE dis=NONE) header.from=siemens.com
Precedence: list
Mailing-list: list jailhouse-dev@googlegroups.com; contact jailhouse-dev+owners@googlegroups.com
List-ID: <jailhouse-dev.googlegroups.com>
X-Spam-Checked-In-Group: jailhouse-dev@googlegroups.com
X-Google-Group-Id: 175645748590
List-Post: <https://groups.google.com/group/jailhouse-dev/post>, <mailto:jailhouse-dev@googlegroups.com>
List-Help: <https://groups.google.com/support/>, <mailto:jailhouse-dev+help@googlegroups.com>
List-Archive: <https://groups.google.com/group/jailhouse-dev
List-Subscribe: <https://groups.google.com/group/jailhouse-dev/subscribe>, <mailto:jailhouse-dev+subscribe@googlegroups.com>
List-Unsubscribe: <mailto:googlegroups-manage+175645748590+unsubscribe@googlegroups.com>,
 <https://groups.google.com/group/jailhouse-dev/subscribe>

T24gMjAuMDIuMjAgMjE6NDgsIFNhcm9qIFNhcGtvdGEgd3JvdGU6DQo+IEZpbmFsbHksIEkgd2Fz
IGFibGUgdG8gaW5zdGFsbCBqYWlsaG91c2UgYW5kIHN1Y2Nlc3NmdWxseSBydW4gYXBpYy1kZW1v
IA0KDQpHcmVhdCENCg0KPiBvbiB0aGUga2l0LiBJIHdhbnQgdG8gY3JlYXRlIG5vbi1yb290IGxp
bnV4IGNlbGw7IEkgdXNlZCANCj4gamV0c29uLXR4MS1saW51eC1kZW1vIGFzIHRlbXBsYXRlIGJ1
dCBJIHdhcyB1bmJsZSB0byBkZWZpbmUgR0lDIGFuZCBwY2kgDQo+IGRldmljZSBhbmQgdnBjaV9p
cnFfYmFzZSBzZXR0aW5nLiBTaW1pbGFybHksIEkgaGF2ZSBwcm9ibGVtIGluIGNyZWF0aW5nIA0K
PiBkdHMgZmlsZSBmb3IgdGhlIHR4MiBoZXJlIGFsc28gSSB1c2VkIGlubWF0ZS10eDEuZHRzIGZp
bGUgYXMgdGVtcGxhdGUuIA0KPiBCb3RoIG9mIHRoZSBmaWxlcyBhcmUgZGlzcGxheWVkIGJlbG93
IHBsZWFzZSBwcm92aWRlIG1lIGhlbHAgdG8gY3JlYXRlIA0KPiB0aGVzZSB0d28gZmlsZXMuDQo+
IHdoYXQgYXJlIHRoZSBuZWNlc3NhcnkgY2hhbmdlcyB0aGF0IGkgaGF2ZSB0byBtYWtlIHBsZWFz
ZSBwcm92aWRlIG1lIA0KPiBzb21lIGhlbHAuDQo+IA0KPiBbMV1saW51eC1jZWxsLWNvbmZpZ3Vy
YXRpb246Ojo6Ojo6Ojo6Ojo6Ojo6Ojo6Ojo6Ojo7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7
Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7
Ozs7Ozs7Ozs7Ow0KPiAjaW5jbHVkZSA8amFpbGhvdXNlL3R5cGVzLmg+DQo+ICNpbmNsdWRlIDxq
YWlsaG91c2UvY2VsbC1jb25maWcuaD4NCj4gDQo+ICNkZWZpbmUgQVJSQVlfU0laRShhKSBzaXpl
b2YoYSkgLyBzaXplb2YoYVswXSkNCj4gDQo+ICNpZm5kZWYgQ09ORklHX0lOTUFURV9CQVNFDQo+
ICNkZWZpbmUgQ09ORklHX0lOTUFURV9CQVNFIDB4MA0KPiAjZW5kaWYNCj4gDQo+IHN0cnVjdCB7
DQo+ICDCoMKgwqAgc3RydWN0IGphaWxob3VzZV9jZWxsX2Rlc2MgY2VsbDsNCj4gIMKgwqDCoCBf
X3U2NCBjcHVzWzFdOw0KPiAgwqDCoMKgIHN0cnVjdCBqYWlsaG91c2VfbWVtb3J5IG1lbV9yZWdp
b25zWzVdOw0KPiAgwqDCoMKgIHN0cnVjdCBqYWlsaG91c2VfaXJxY2hpcCBpcnFjaGlwc1szXTsN
Cj4gIMKgwqDCoCBzdHJ1Y3QgamFpbGhvdXNlX3BjaV9kZXZpY2UgcGNpX2RldmljZXNbMV07DQo+
IH0gX19hdHRyaWJ1dGVfXygocGFja2VkKSkgY29uZmlnID0gew0KPiAgwqDCoMKgIC5jZWxsID0g
ew0KPiAgwqDCoMKgIMKgwqDCoCAuc2lnbmF0dXJlID0gSkFJTEhPVVNFX0NFTExfREVTQ19TSUdO
QVRVUkUsDQo+ICDCoMKgwqAgwqDCoMKgIC5yZXZpc2lvbiA9IEpBSUxIT1VTRV9DT05GSUdfUkVW
SVNJT04sDQo+ICDCoMKgwqAgwqDCoMKgIC5uYW1lID0gImpldHNvbi10eDItbGludXgtZGVtbyIs
DQo+ICDCoMKgwqAgwqDCoMKgIC5mbGFncyA9IEpBSUxIT1VTRV9DRUxMX1BBU1NJVkVfQ09NTVJF
RyB8DQo+ICDCoMKgwqAgwqDCoMKgIMKgwqDCoCDCoEpBSUxIT1VTRV9DRUxMX0RFQlVHX0NPTlNP
TEUsDQo+IA0KPiAgwqDCoMKgIMKgwqDCoCAuY3B1X3NldF9zaXplID0gc2l6ZW9mKGNvbmZpZy5j
cHVzKSwNCj4gIMKgwqDCoCDCoMKgwqAgLm51bV9tZW1vcnlfcmVnaW9ucyA9IEFSUkFZX1NJWkUo
Y29uZmlnLm1lbV9yZWdpb25zKSwNCj4gIMKgwqDCoCDCoMKgwqAgLm51bV9pcnFjaGlwcyA9IEFS
UkFZX1NJWkUoY29uZmlnLmlycWNoaXBzKSwNCj4gIMKgwqDCoCDCoMKgwqAgLm51bV9wY2lfZGV2
aWNlcyA9IEFSUkFZX1NJWkUoY29uZmlnLnBjaV9kZXZpY2VzKSwNCj4gDQo+ICrCoCAudnBjaV9p
cnFfYmFzZSA9IDI2MCwgLyoxNTIqLyAvL2hvdyB0byBnZXQgKGZyb20gd2hlcmUgSSBjYW4gZ2V0
KSANCj4gdnBjaV9pcnFfYmFzZSAqDQoNCkRlcGVuZGluZyBvbiB0aGUgbnVtYmVyIG9mIGl2c2ht
ZW0gZGV2aWNlcyBhc3NpZ25lZCB0byB0aGUgY2VsbCwgeW91IA0KbmVlZCBhIHNldCBvZiAxIHRv
IDQgZnJlZSBpbnRlcnJ1cHQgbnVtYmVycyAobm90IHVzZWQgYnkgYW55IHBoeXNpY2FsIA0KZGV2
aWNlcyBpbiB1c2UgYnkgYW55IGNlbGwpIHRoYXQgYXJlIHN0aWxsIGluIHRoZSBzdXBwb3J0ZWQg
cmFuZ2Ugb2YgdGhlIA0KaW50ZXJydXB0IGNvbnRyb2xsZXIuIENoZWNrIHRoZSBHSUMgaW50ZXJy
dXB0IG51bWJlcnMgTGludXggbGlzdHMgaW4gDQovcHJvYy9pbnRlcnJ1cHQgb24gdGhlIHJpZ2h0
IHNpZGUgd2hpbGUgaXQgaXMgaW4gY2hhcmdlIG9mIGFsbCBoYXJkd2FyZSANCmFuZCBzZWxlY3Qg
YSBmcmVlIHJhbmdlLiBOb3RlIHRoYXQgdmNwaV9pcnFfYmFzZSBpcyBhbiBTUEkgb24gQVJNIHdo
aWxlIA0KTGludXggbGlzdCBpbnRlcnJ1cHQgSURzIChTUElzIHN0YXJ0IGF0IGludGVycnVwdCBJ
RCAzMikuDQoNCj4gDQo+ICDCoMKgwqAgwqDCoMKgIC5jcHVfcmVzZXRfYWRkcmVzcyA9IENPTkZJ
R19JTk1BVEVfQkFTRSwNCj4gIMKgwqDCoCB9LA0KPiANCj4gIMKgwqDCoCAuY3B1cyA9IHsNCj4g
IMKgwqDCoCDCoMKgwqAgMHgzMCwvKjB4YyBmb3IgdHgxKi8NCj4gIMKgwqDCoCB9LA0KPiANCj4g
IMKgwqDCoCAubWVtX3JlZ2lvbnMgPSB7DQo+ICDCoMKgwqAgwqDCoMKgIC8qIFVBUlQgKi8gew0K
PiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgLnBoeXNfc3RhcnQgPSAweDMxMDAwMDAsLyoweDcwMDA2
MDAwKi8NCj4gIMKgwqDCoCDCoMKgwqAgwqDCoMKgIC52aXJ0X3N0YXJ0ID0gMHgzMTAwMDAwLA0K
PiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgLnNpemUgPSAweDEwMDAsDQo+ICDCoMKgwqAgwqDCoMKg
IMKgwqDCoCAuZmxhZ3MgPSBKQUlMSE9VU0VfTUVNX1JFQUQgfCBKQUlMSE9VU0VfTUVNX1dSSVRF
IHwNCj4gIMKgwqDCoCDCoMKgwqAgwqDCoMKgIMKgwqDCoCBKQUlMSE9VU0VfTUVNX0lPIHwgSkFJ
TEhPVVNFX01FTV9ST09UU0hBUkVELA0KPiAgwqDCoMKgIMKgwqDCoCB9LA0KPiAgwqDCoMKgIMKg
wqDCoCAvKiBSQU0gKi8gew0KPiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgLnBoeXNfc3RhcnQgPSAw
eDI2ZWYwMDAwMCwvKjB4MTdiZWYwMDAwKi8NCj4gIMKgwqDCoCDCoMKgwqAgwqDCoMKgIC52aXJ0
X3N0YXJ0ID0gQ09ORklHX0lOTUFURV9CQVNFLA0KPiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgLnNp
emUgPSAweDEwMDAwLA0KPiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgLmZsYWdzID0gSkFJTEhPVVNF
X01FTV9SRUFEIHwgSkFJTEhPVVNFX01FTV9XUklURSB8DQo+ICDCoMKgwqAgwqDCoMKgIMKgwqDC
oCDCoMKgwqAgSkFJTEhPVVNFX01FTV9FWEVDVVRFIHwgSkFJTEhPVVNFX01FTV9ETUEgfA0KPiAg
wqDCoMKgIMKgwqDCoCDCoMKgwqAgwqDCoMKgIEpBSUxIT1VTRV9NRU1fTE9BREFCTEUsDQo+ICDC
oMKgwqAgwqDCoMKgIH0sDQo+ICDCoMKgwqAgwqDCoMKgIC8qIFJBTSAqLyB7DQo+ICDCoMKgwqAg
wqDCoMKgIMKgwqDCoCAucGh5c19zdGFydCA9IDB4MjUyZDAwMDAwLC8qMHgxNjEyMDAwMDAqLw0K
PiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgLnZpcnRfc3RhcnQgPSAweGU4MDAwMDAwLC8qdG8gZG8q
Lw0KPiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgLnNpemUgPSAweDFjMjAwMDAwLC8qMHgxYWNmMDAw
MCovDQo+ICDCoMKgwqAgwqDCoMKgIMKgwqDCoCAuZmxhZ3MgPSBKQUlMSE9VU0VfTUVNX1JjRUFE
IHwgSkFJTEhPVVNFX01FTV9XUklURSB8DQo+ICDCoMKgwqAgwqDCoMKgIMKgwqDCoCDCoMKgwqAg
SkFJTEhPVVNFX01FTV9FWEVDVVRFIHwgSkFJTEhPVVNFX01FTV9ETUEgfA0KPiAgwqDCoMKgIMKg
wqDCoCDCoMKgwqAgwqDCoMKgIEpBSUxIT1VTRV9NRU1fTE9BREFCTEUsDQo+ICDCoMKgwqAgwqDC
oMKgIH0sDQo+ICDCoMKgwqAgwqDCoMKgIC8qIElWU0hNRU0gc2hhcmVkIG1lbW9yeSByZWdpb24g
Ki8gew0KPiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgLnBoeXNfc3RhcnQgPSAweDI2ZjAwMDAwMCwv
KjB4MTdiZjAwMDAwLCovDQo+ICDCoMKgwqAgwqDCoMKgIMKgwqDCoCAudmlydF9zdGFydCA9IDB4
MjZmMDAwMDAwLA0KPiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgLnNpemUgPSAweDEwMDAwMCwNCj4g
IMKgwqDCoCDCoMKgwqAgwqDCoMKgIC5mbGFncyA9IEpBSUxIT1VTRV9NRU1fUkVBRCB8IEpBSUxI
T1VTRV9NRU1fV1JJVEUgfA0KPiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgwqDCoMKgIEpBSUxIT1VT
RV9NRU1fUk9PVFNIQVJFRCwNCj4gIMKgwqDCoCDCoMKgwqAgfSwNCj4gIMKgwqDCoCDCoMKgwqAg
LyogY29tbXVuaWNhdGlvbiByZWdpb24gKi8gew0KPiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgLnZp
cnRfc3RhcnQgPSAweDgwMDAwMDAwLA0KPiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgLnNpemUgPSAw
eDAwMDAxMDAwLA0KPiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgLmZsYWdzID0gSkFJTEhPVVNFX01F
TV9SRUFEIHwgSkFJTEhPVVNFX01FTV9XUklURSB8DQo+ICDCoMKgwqAgwqDCoMKgIMKgwqDCoCDC
oMKgwqAgSkFJTEhPVVNFX01FTV9DT01NX1JFR0lPTiwNCj4gIMKgwqDCoCDCoMKgwqAgfSwNCj4g
IMKgwqDCoCB9LA0KPiANCj4gIMKgwqDCoCAuaXJxY2hpcHMgPSB7DQo+ICDCoMKgwqAgwqDCoMKg
IC8qIEdJQyAqLyB7DQo+ICDCoMKgwqAgwqDCoMKgIMKgwqDCoCAuYWRkcmVzcyA9IDB4MDM4ODEw
MDAsLyoweDUwMDQxMDAwLCovDQo+ICoucGluX2Jhc2UgPSAzMiwNCj4gIMKgwqDCoCDCoMKgwqAg
wqDCoMKgIC5waW5fYml0bWFwID0gew0KPiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgwqDCoMKgIDAs
ICgxIDw8ICgzNiAlIDMyKSksIDAsIDAgLy9ob3cgdG8gc2V0IHRoaXMgLnBpbl9iaXRtYXAgDQo+
ICYgd2hlcmUgSSBjYW4gZmluZCB0aGUgcGluIGRldGFpbHMqDQo+ICDCoMKgwqAgwqDCoMKgIMKg
wqDCoCB9LA0KDQpUaGUgaW50ZXJydXB0cyAoSURzLCB0aHVzIDAtYmFzZWQpIHRoaXMgY2VsbCBz
aG91bGQgY29udHJvbCwgaW5jbHVkaW5nIA0KdGhvc2Ugb2YgdGhlIHZpcnR1YWwgaXZzaG1lbSBk
ZXZpY2VzLiBBcyBwaW5fYml0bWFwIGlzIGxpbWl0ZWQgdG8gMTI4IA0KcGlucywgeW91IGNhbiB1
c2UgbXVsdGlwbGUgZW50cmllcyB3aXRoIGRpZmZlcmVudCBwaW5fYmFzZSB0byBkZXNjcmliZSBh
IA0Kd2lkZXIgc2V0Lg0KDQo+ICDCoMKgwqAgwqDCoMKgIH0sDQo+ICDCoMKgwqAgwqDCoMKgIC8q
IEdJQyAqLyB7DQo+ICDCoMKgwqAgwqDCoMKgIMKgwqDCoCAuYWRkcmVzcyA9IDB4MDM4ODEwMDAs
DQo+ICoucGluX2Jhc2UgPSAxNjAsDQo+ICDCoMKgwqAgwqDCoMKgIMKgwqDCoCAucGluX2JpdG1h
cCA9IHsNCj4gIMKgwqDCoCDCoMKgwqAgwqDCoMKgIMKgwqDCoCAxIDw8ICgyNjArMzIgLSAxNjAp
LC8qMTw8KDE1MiszMi0xNjApIGZvciB0eDEqLyAqKi8vaG93IA0KPiB0byBzZXQgdGhpcyAucGlu
X2JpdG1hcCAmIHdoZXJlIEkgY2FuIGZpbmQgdGhlIHBpbiBkZXRhaWxzKg0KPiAgwqDCoMKgIMKg
wqDCoCDCoMKgwqAgfSwNCj4gIMKgwqDCoCDCoMKgwqAgfSwNCj4gIMKgwqDCoCDCoMKgwqAgLyog
R0lDICovIHsNCj4gIMKgwqDCoCDCoMKgwqAgwqDCoMKgIC5hZGRyZXNzID0gMHgwMzg4MTAwMCwv
Km5ld2x5IGFkZGVkIGZvciB0eDIqLw0KPiAqLnBpbl9iYXNlID0gMjg4LA0KPiAgwqDCoMKgIMKg
wqDCoCDCoMKgwqAgLnBpbl9iaXRtYXAgPSB7DQo+ICDCoMKgwqAgwqDCoMKgIMKgwqDCoCDCoMKg
wqAgMSA8PCAoMjYwKzMyKzE2MCAtIDI4OCksKioqKi8vaG93IHRvIHNldCB0aGlzIA0KPiAucGlu
X2JpdG1hcCAmIHdoZXJlIEkgY2FuIGZpbmQgdGhlIHBpbiBkZXRhaWxzKg0KPiAgwqDCoMKgIMKg
wqDCoCDCoMKgwqAgfSwNCj4gIMKgwqDCoCDCoMKgwqAgfSwNCj4gIMKgwqDCoCB9LA0KPiANCj4g
IMKgwqDCoCAucGNpX2RldmljZXMgPSB7DQo+ICrCoCAvKiAwMDowMC4wICovIHsNCj4gIMKgwqDC
oCDCoMKgwqAgwqDCoMKgIC50eXBlID0gSkFJTEhPVVNFX1BDSV9UWVBFX0lWU0hNRU0sDQo+ICDC
oMKgwqAgwqDCoMKgIMKgwqDCoCAuYmRmID0gMHgwMCwNCj4gIMKgwqDCoCDCoMKgwqAgwqDCoMKg
IC5iYXJfbWFzayA9IHsgLy9ob3cgdG8gZGVmaW5lIGJhcl9tYXNrPw0KPiAgwqDCoMKgIMKgwqDC
oCDCoMKgwqAgwqDCoMKgIDB4ZmZmZmZmMDAsIDB4ZmZmZmZmZmYsIDB4MDAwMDAwMDAsDQo+ICDC
oMKgwqAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgMHgwMDAwMDAwMCwgMHgwMDAwMDAwMCwgMHgwMDAw
MDAwMCwNCg0KWW91IGFyZSBwb3NzaWJseSBub3Qgb24gdmVyc2lvbiAwLjEyLiBUaGF0IG9uZSBo
YXMgDQpKQUlMSE9VU0VfSVZTSE1FTV9CQVJfTUFTS19JTlRYIHdoaWNoIHlvdSB3YW50IHRvIHVz
ZSBoZXJlLg0KDQo+ICDCoMKgwqAgwqDCoMKgIMKgwqDCoCB9LA0KPiAgwqDCoMKgIMKgwqDCoCDC
oMKgwqAgLnNobWVtX3JlZ2lvbiA9IDMsKg0KPiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgLnNobWVt
X3Byb3RvY29sID0gSkFJTEhPVVNFX1NITUVNX1BST1RPX1ZFVEgsDQo+ICDCoMKgwqAgwqDCoMKg
IH0sDQo+ICDCoMKgwqAgfSwNCj4gfTsNCj4gDQo+IFsyXSBkdHMgDQo+IGZpbGU6Ojo6Ojo6Ojo6
Ojo6Ojo6Ojo6Ojo6Ojs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7
Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsN
Cj4gI2luY2x1ZGUgPGR0LWJpbmRpbmdzL2ludGVycnVwdC1jb250cm9sbGVyL2FybS1naWMuaD4N
Cj4gDQo+IC9kdHMtdjEvOw0KPiANCj4gLyB7DQo+ICDCoMKgwqAgbW9kZWwgPSAiSmFpbGhvdXNl
IGNlbGwgb24gTlZJRElBIEpldHNvbiBUWDIiOw0KPiANCj4gIMKgwqDCoCAjYWRkcmVzcy1jZWxs
cyA9IDwxPjsNCj4gIMKgwqDCoCAjc2l6ZS1jZWxscyA9IDwxPjsNCj4gDQo+ICDCoMKgwqAgaW50
ZXJydXB0LXBhcmVudCA9IDwmZ2ljPjsNCj4gDQo+ICDCoMKgwqAgaHlwZXJ2aXNvciB7DQo+ICDC
oMKgwqAgwqDCoMKgIGNvbXBhdGlibGUgPSAiamFpbGhvdXNlLGNlbGwiOw0KPiAgwqDCoMKgIH07
DQo+IA0KPiAgwqDCoMKgIGNwdXMgew0KPiAgwqDCoMKgIMKgwqDCoCAjYWRkcmVzcy1jZWxscyA9
IDwxPjsNCj4gIMKgwqDCoCDCoMKgwqAgI3NpemUtY2VsbHMgPSA8MD47DQo+IA0KPiAgwqDCoMKg
IMKgwqDCoCBjcHVANCB7DQo+ICDCoMKgwqAgwqDCoMKgIMKgwqDCoCBjb21wYXRpYmxlID0gImFy
bSxjb3J0ZXgtYTU3IjsNCj4gIMKgwqDCoCDCoMKgwqAgwqDCoMKgIGRldmljZV90eXBlID0gImNw
dSI7DQo+ICDCoMKgwqAgwqDCoMKgIMKgwqDCoCBlbmFibGUtbWV0aG9kID0gInBzY2kiOw0KPiAg
wqDCoMKgIMKgwqDCoCDCoMKgwqAgcmVnID0gPDB4ND47DQo+ICDCoMKgwqAgwqDCoMKgIH07DQo+
IA0KPiAgwqDCoMKgIMKgwqDCoCBjcHVANSB7DQo+ICDCoMKgwqAgwqDCoMKgIMKgwqDCoCBjb21w
YXRpYmxlID0gImFybSxjb3J0ZXgtYTU3IjsNCj4gIMKgwqDCoCDCoMKgwqAgwqDCoMKgIGRldmlj
ZV90eXBlID0gImNwdSI7DQo+ICDCoMKgwqAgwqDCoMKgIMKgwqDCoCBlbmFibGUtbWV0aG9kID0g
InBzY2kiOw0KPiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgcmVnID0gPDB4NT47DQo+ICDCoMKgwqAg
wqDCoMKgIH07DQo+ICDCoMKgwqAgfTsNCj4gDQo+ICDCoMKgwqAgcHNjaSB7DQo+ICDCoMKgwqAg
wqDCoMKgIGNvbXBhdGlibGUgPSAiYXJtLHBzY2ktMC4yIjsNCj4gIMKgwqDCoCDCoMKgwqAgbWV0
aG9kID0gInNtYyI7DQo+ICDCoMKgwqAgfTsNCj4gDQo+ICDCoMKgwqAgZ2ljOiBpbnRlcnJ1cHQt
Y29udHJvbGxlckAwMzg4MTAwMCB7DQo+ICDCoMKgwqAgwqDCoMKgIGNvbXBhdGlibGUgPSAiYXJt
LGdpYy00MDAiOw0KPiAgwqDCoMKgIMKgwqDCoCAjaW50ZXJydXB0LWNlbGxzID0gPDM+Ow0KPiAg
wqDCoMKgIMKgwqDCoCBpbnRlcnJ1cHQtY29udHJvbGxlcjsNCj4gIMKgwqDCoCDCoMKgwqAgcmVn
ID0gPDB4MDM4ODEwMDAgMHgxMDAwPiwgLyoweDUwMDQxMDAwIDB4MTAwMCBmb3IgdHgxLw0KPiAg
wqDCoMKgIMKgwqDCoCDCoMKgwqDCoMKgIDwweDAzODgyMDAwIDB4MTAwMD47DQo+ICDCoMKgwqAg
fTsNCj4gDQo+ICDCoMKgwqAgdGltZXIgew0KPiAgwqDCoMKgIMKgwqDCoCBjb21wYXRpYmxlID0g
ImFybSxhcm12OC10aW1lciI7DQo+ICDCoMKgwqAgwqDCoMKgIGludGVycnVwdHMgPSA8R0lDX1BQ
SSAxMyAqLy9pcyB0aGlzIHNhbWUgZm9yIGFsbCBhcm12OCANCj4gYXJjaGl0ZWN0dXJlICoNCj4g
IMKgwqDCoCDCoMKgwqAgwqDCoMKgIMKgwqDCoCAoR0lDX0NQVV9NQVNLX1NJTVBMRSg0KSB8IElS
UV9UWVBFX0xFVkVMX0xPVyk+LA0KPiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgwqDCoMKgwqAgPEdJ
Q19QUEkgMTQNCj4gIMKgwqDCoCDCoMKgwqAgwqDCoMKgIMKgwqDCoCAoR0lDX0NQVV9NQVNLX1NJ
TVBMRSg0KSB8IElSUV9UWVBFX0xFVkVMX0xPVyk+LA0KPiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAg
wqDCoMKgwqAgPEdJQ19QUEkgMTENCj4gIMKgwqDCoCDCoMKgwqAgwqDCoMKgIMKgwqDCoCAoR0lD
X0NQVV9NQVNLX1NJTVBMRSg0KSB8IElSUV9UWVBFX0xFVkVMX0xPVyk+LA0KPiAgwqDCoMKgIMKg
wqDCoCDCoMKgwqAgwqDCoMKgwqAgPEdJQ19QUEkgMTANCj4gIMKgwqDCoCDCoMKgwqAgwqDCoMKg
IMKgwqDCoCAoR0lDX0NQVV9NQVNLX1NJTVBMRSg0KSB8IElSUV9UWVBFX0xFVkVMX0xPVyk+Ow0K
PiAgwqDCoMKgIMKgwqDCoCBpbnRlcnJ1cHQtcGFyZW50ID0gPCZnaWM+Ow0KPiAgwqDCoMKgIH07
DQo+IA0KPiAgwqDCoMKgIHNlcmlhbEAzMTAwMDAwMCB7DQo+ICDCoMKgwqAgwqDCoMKgIGNvbXBh
dGlibGUgPSAibnZpZGlhLHRlZ3JhMjEwLXVhcnQiLCAibnZpZGlhLHRlZ3JhMjAtdWFydCI7DQo+
ICDCoMKgwqAgwqDCoMKgIHJlZyA9IDwweDMxMDAwMDAwIDB4NDA+O8KgwqDCoMKgwqDCoMKgwqDC
oMKgwqDCoMKgwqDCoMKgIC8qMHg3MDAwNjAwMCAweDQwIGZvciANCj4gdHgxICoqLyAvL3doYXRz
IHRoZSAweDQwIGhlcmUgZG9lcyB0aGlzIG5lZWQgdG8gYmUgY2hhbmdlZCoNCg0KVGhhdCdzIHRo
ZSBzaXplIG9mIHRoZSByZWdpc3RlciByZWdpb24uIFRha2Ugd2hhdCB0aGUgbWFpbiBkZXZpY2Ug
dHJlZSANCmxpc3RzIGFzIHdlbGwuDQoNCj4gIMKgwqDCoCDCoMKgwqAgcmVnLXNoaWZ0ID0gPDI+
Ow0KPiAgwqDCoMKgIMKgwqDCoCBpbnRlcnJ1cHRzID0gPEdJQ19TUEkgMzYgSVJRX1RZUEVfTEVW
RUxfSElHSD47DQo+ICrCoCBjbG9jay1mcmVxdWVuY3kgPSA8NDA4MDAwMDAwPjsvL2hvdyB0byBk
ZWZpbmUgY2xvY2sgZnJlcXVlbmN5IHdoZXJlIA0KPiB0byBsb29rKg0KDQpUaGlzIGlzIGluZGVl
ZCB0cmlja3kuIElmIHlvdSBhcmUgbHVja3ksIHRoZSBtYWluIGR0cyBoYXMgYSB2YWx1ZS4gSWYg
DQpub3QsIHlvdSBoYXZlIGEgcG9pbnRlciB0byBjbG9jayB0cmVlLCBhbmQgaXQgY2FuIGJlIGhh
cmQgdG8gZGVyaXZlIHRoZSANCmVmZmVjdGl2ZSBmcmVxdWVuY3kgb24gdGhlIHVhcnQgZnJvbSB0
aGF0LiBJbiBzb21lIGNhc2VzLCBJIGp1c3QgDQppbnN0cnVtZW50ZWQgdGhlIGRyaXZlciB0byBw
cmludCBvdXQgdGhlIGZyZXF1ZW5jeSBvZiB0aGUgY2xvY2sgaXQgc2VsZWN0ZWQuDQoNCj4gIMKg
wqDCoCDCoMKgwqAgc3RhdHVzID0gIm9rYXkiOw0KPiAgwqDCoMKgIH07DQo+IA0KPiAgwqDCoMKg
IHBjaUA0MDAwMDAwMCANCj4ge8KgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKg
wqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDC
oMKgwqDCoMKgwqDCoCAvKjQ4MDAwMDAwIHR4MSovDQo+ICDCoMKgwqAgwqDCoMKgIHN0YXR1cyA9
ICJva2F5IjsNCj4gIMKgwqDCoCDCoMKgwqAgY29tcGF0aWJsZSA9ICJwY2ktaG9zdC1lY2FtLWdl
bmVyaWMiOw0KPiAgwqDCoMKgIMKgwqDCoCBkZXZpY2VfdHlwZSA9ICJwY2kiOw0KPiAgwqDCoMKg
IMKgwqDCoCBidXMtcmFuZ2UgPSA8MCAwPjsNCj4gIMKgwqDCoCDCoMKgwqAgI2FkZHJlc3MtY2Vs
bHMgPSA8Mz47DQo+ICDCoMKgwqAgwqDCoMKgICNzaXplLWNlbGxzID0gPDI+Ow0KPiAgwqDCoMKg
IMKgwqDCoCAjaW50ZXJydXB0LWNlbGxzID0gPDE+Ow0KPiAqwqAgaW50ZXJydXB0LW1hcC1tYXNr
ID0gPDAgMCAwIDc+Oy8vaG93IHRvIGRlZmluZSBpbnRlcnJ1cHQtbWFwLW1hc2sNCj4gIMKgwqDC
oCDCoMKgwqAgaW50ZXJydXB0LW1hcCA9IDwwIDAgMCAxICZnaWMgR0lDX1NQSSAxNTIgDQo+IElS
UV9UWVBFX0VER0VfUklTSU5HPiwvL2hvdyB0byBzZXQgaW50ZXJydXB0LW1hcCwgaSB0aGluayBp
IGhhdmUgc2V0IGl0IA0KPiB3cm9uZ2x5Lg0KPiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgwqDCoMKg
IDwwIDAgMCAyICZnaWMgR0lDX1NQSSAyNjAgSVJRX1RZUEVfRURHRV9SSVNJTkc+LC8qMTUyIA0K
PiBmb3IgdHgxKi8NCj4gIMKgwqDCoCDCoMKgwqAgwqDCoMKgIMKgwqDCoCA8MCAwIDAgMyAmZ2lj
IEdJQ19TUEkgMjYxIElSUV9UWVBFX0VER0VfUklTSU5HPiwsLyoxNTMgDQo+IGZvciB0eDEqLw0K
PiAgwqDCoMKgIMKgwqDCoCDCoMKgwqAgwqDCoMKgIDwwIDAgMCA0ICZnaWMgR0lDX1NQSSAyNjIg
SVJRX1RZUEVfRURHRV9SSVNJTkc+OywvKjE1NCANCj4gZm9yIHR4MSovKg0KDQpEbyBub3QgY2hh
bmdlIGFueXRoaW5nIGJ5IHRoZSBTUEkgbnVtYmVycy4gdnBjaV9pcnFfYmFzZSBnb2VzIGludG8g
dGhlIA0KZmlyc3QgbGluZSwgdGhlbiArMSBmb3IgbmV4dCBhbmQgc28gb24uIEFuIGl2c2htZW0g
ZGV2aWNlIG9uIGRldmljZSBzbG90IA0KMCAoMDA6MDAuMCkgd2lsbCB0YWtlIHRoZSBmaXJzdCBs
aW5lLCBhIGRldmljZSBhbiBzbG90IDEgKDAwOjAxLjApIHRoZSANCnNlY29uZCBldGMuDQoNCj4g
KnJlZyA9IDwweDQwMDAwMDAwIDB4MTAwMDAwPjsvL2hvdyB0byBkZWZpbmUgcmVnIGZvciB0eDIN
Cj4gIMKgwqDCoCDCoMKgwqAgcmFuZ2VzID0NCj4gIMKgwqDCoCDCoMKgwqAgwqDCoMKgIDwweDAy
MDAwMDAwIDB4MDAgMHgxMDAwMDAwMCAweDEwMDAwMDAwIDB4MDAgMHgxMDAwMD47Ly9ob3cgDQo+
IHRvIGRlZmluZSByYW5nZXMgZm9yIHR4MioNCj4gIMKgwqDCoCB9Ow0KPiB9Ow0KDQpKYW4NCg0K
LS0gDQpTaWVtZW5zIEFHLCBDb3Jwb3JhdGUgVGVjaG5vbG9neSwgQ1QgUkRBIElPVCBTRVMtREUN
CkNvcnBvcmF0ZSBDb21wZXRlbmNlIENlbnRlciBFbWJlZGRlZCBMaW51eA0KDQotLSAKWW91IHJl
Y2VpdmVkIHRoaXMgbWVzc2FnZSBiZWNhdXNlIHlvdSBhcmUgc3Vic2NyaWJlZCB0byB0aGUgR29v
Z2xlIEdyb3VwcyAiSmFpbGhvdXNlIiBncm91cC4KVG8gdW5zdWJzY3JpYmUgZnJvbSB0aGlzIGdy
b3VwIGFuZCBzdG9wIHJlY2VpdmluZyBlbWFpbHMgZnJvbSBpdCwgc2VuZCBhbiBlbWFpbCB0byBq
YWlsaG91c2UtZGV2K3Vuc3Vic2NyaWJlQGdvb2dsZWdyb3Vwcy5jb20uClRvIHZpZXcgdGhpcyBk
aXNjdXNzaW9uIG9uIHRoZSB3ZWIgdmlzaXQgaHR0cHM6Ly9ncm91cHMuZ29vZ2xlLmNvbS9kL21z
Z2lkL2phaWxob3VzZS1kZXYvOTk4ODRiNjMtMmU0MC0zYjY0LTg2ZmEtZmYyZDljODQ1N2E5JTQw
c2llbWVucy5jb20uCg==
